# -*- mode: ruby -*-
# vi: set ft=ruby :

driveletters = ('a'..'z').to_a

Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
  config.vm.network "forwarded_port", guest: 30600, host: 9090, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 30800, host: 9000, host_ip: "127.0.0.1"

  config.vm.box = "centos/atomic-host"
  host_vars = {}
  (1..3).each do |i|
    config.vm.define vm_name = "kube#{i}" do |vm|
      vm.vm.hostname = vm_name

      vm.vm.provider :libvirt do |lv|
        lv.default_prefix = "gcs"
        lv.cpus = 2
        lv.memory = 2048

        lv.storage :file, :device => "vdb", :size => '20G'

        disks = []
        (2..4).each do |d|
          lv.storage :file, :device => "vd#{driveletters[d]}", :size => '1024G'
          disks.push "/dev/vd#{driveletters[d]}"
        end
        host_vars[vm_name] = {"gcs_disks" => disks.to_s}
      end
      # TODO: Maybe support other providers... like VirtualBox

      if i == 3
        vm.vm.provision :ansible do |ansible|
          ansible.playbook = "vagrant-playbook.yml"
          ansible.become = true
          ansible.limit = "all"
          ansible.groups = {
            "etcd" => ["kube[1:3]"],
            "kube-master" => ["kube[1:2]"],
            "kube-node" => ["kube[1:3]"],
            "k8s-cluster:children" => ["kube-master", "kube-node"],
            "gcs-node" => ["kube[1:3]"]
          }
          ansible.host_vars = host_vars
        end
      end
    end
  end
end
