# -*- mode: ruby -*-
# vi: set ft=ruby :

driveletters = ('a'..'z').to_a

Vagrant.configure("2") do |config|
  # This Vagrantfile works with only vagrant-libvirt right now
  # Ensure that the vagrant-libvirt plugin is present
  config.vagrant.plugins = ["vagrant-libvirt"]

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true

  config.vm.box = "centos/atomic-host"
  (1..3).each do |i|
    config.vm.define "kube#{i}" do |vm|
      vm.vm.hostname = "kube#{i}"

      vm.vm.provider :libvirt do |lv|
        lv.default_prefix = "gcs"
        lv.cpus = 2
        lv.memory = 2048

        (1..3).each do |d|
          lv.storage :file, :device => "vd#{driveletters[d]}", :size => '1024G'
        end
      end
      # TODO: Maybe support other providers... like VirtualBox

      if i == 3
        vm.vm.provision :ansible do |ansible|
          ansible.playbook = "vagrant-playbook.yml"
          ansible.become = true
          ansible.limit = "all"
          ansible.groups = {
            "etcd" => ["kube[1:3]"],
            "kube-master" => ["kube[1:2]"],
            "kube-node" => ["kube[1:3]"],
            "k8s-cluster:children" => ["kube-master", "kube-node"]
          }
        end
      end
    end
  end
end
